### ISSUE TITLE
您好，有个认证流程的问题想请教下

### ISSUE THREAD

**Issue by dragenr** [vv314/xiaoai-tts#11]
通过您代码我用php实现了get_Sign和get_ServerToken两个接口并且算出clientSign密钥
但是在loginmiai动作这里我get的接口返回是400，无法拿到setcookie字段，检查了数遍请求头和参数是一样的，并且同一台服务器使用node跑您的代码一切正常，请问是我忽略了什么细节吗

**Comment by vv314** [comment]
不同的请求库，底层实现不一样，最终发出去的请求未必相同，比如有的库会自动补充一些常用 header。
状态 400 可能是缺少了某些必要 header，建议使用抓包工具或代理工具调试，抓取出口请求进行对比。

**Comment by dragenr** [comment]
好的谢谢我尝试尝试
