### ISSUE TITLE
playUrl

### ISSUE THREAD

**Issue by ReviewClouds** [vv314/xiaoai-tts#5]
playUrl 的地址是什么样的，我测试了在线的网易云和qq音乐的地址都不行呢，还是需要下载好音乐，然后从自己的服务器上输入地址吗；能否提供一个url

**Comment by ReviewClouds** [comment]
可以了，使用自己服务器上的mp3和wav可以播放

**Comment by vv314** [comment]
http://ting6.yymp3.net:82/new12/fanweiqi8/11.mp3
音频类型的资源地址，指令发出后需要一定的时间缓冲
