### ISSUE TITLE
TTS功能好像失效

### ISSUE THREAD

**Issue by zhuzhuyule** [vv314/xiaoai-tts#8]
音量大小可以控制，可以暂停，但是 TTS 没有反应，也没有报错。求指导

**Comment by zhuzhuyule** [comment]
好像不是所有的音箱都支持：
支持：Redme小爱音箱Play, 小爱音箱Pro
不支持：万能遥控版，带时间万能遥控板，小爱触屏音箱，红米触屏音箱

**Comment by vv314** [comment]
感谢反馈，目前手头测试过的设备只有小爱 mini，后续会再分析下数据
